

/**
 * Constants for common style.
 */
export class StyleConstants {
  /**
   * Component width percentage: 100%.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Component height percentage: 100%.
   */
  static readonly FULL_HEIGHT: string = '100%';

  /**
   * Component height percentage: 70%.
   */
  static readonly SEVENTY_HEIGHT: string = '70%';

  /**
   * Component height percentage: 60%.
   */
  static readonly SIXTY_HEIGHT: string = '60%';

  /**
   * Component width percentage: 60%.
   */
  static readonly SIXTY_WIDTH: string = '60%';

  /**
   * Component height percentage: 50%.
   */
  static readonly FIFTY_HEIGHT: string = '50%';

  /**
   * Component height percentage: 50%.
   */
  static readonly HUNDRED_FIFTEEN_WIDTH: string = '115%';

  /**
   * Component space vp : 4.
   */
  static readonly FOUR_SPACE: string = '4vp';

  /**
   * Component space vp : 12.
   */
  static readonly TWELVE_SPACE: string = '12vp';

  /**
   * Component space vp : 14.
   */
  static readonly ITEM_SPACE: string = '14vp';

  /**
   * Component space vp : 15.
   */
  static readonly FIFTEEN_SPACE: string = '15vp';

  /**
   * Font weight value: 700.
   */
  static readonly FONT_WEIGHT_SEVEN: number = 700;

  /**
   * Font weight value: 500.
   */
  static readonly FONT_WEIGHT_FIVE: number = 500;

  /**
   * Font weight value: 400.
   */
  static readonly FONT_WEIGHT_FOUR: number = 400;

  /**
   * Text line value: 2.
   */
  static readonly TWO_TEXT_LINE: number = 2;

  /**
   * Component opacity value: 1.
   */
  static readonly FULL_OPACITY: number = 1;

  /**
   * Component opacity value: 0.6.
   */
  static readonly SIXTY_OPACITY: number = 0.6;

  /**
   * Component opacity value: 0.8.
   */
  static readonly EIGHTY_OPACITY: number = 0.8;

  /**
   * Component layout value: 1.
   */
  static readonly LAYOUT_WEIGHT: number = 1;

  /**
   * Flex basic value: 1.
   */
  static readonly FLEX_BASIC: number = 1;

  /**
   * Flex shrink value: 1.
   */
  static readonly FLEX_SHRINK: number = 1;

  /**
   * Flex grow value: 1.
   */
  static readonly FLEX_GROW: number = 1;

  /**
   * Swiper or list display count value: 1.
   */
  static readonly DISPLAY_ONE: number = 1;

  /**
   * Swiper or list display count value: 2.
   */
  static readonly DISPLAY_TWO: number = 2;

  /**
   * Swiper or list display count value: 3.
   */
  static readonly DISPLAY_THREE: number = 3;

  /**
   * Swiper or list display count value: 4.
   */
  static readonly DISPLAY_FOUR: number = 4;

  /**
   * Image aspect ratio value: 2.23.
   */
  static readonly IMAGE_ASPECT_RATIO: number = 2.25;

  /**
   * Number of value: 0.5.
   */
  static readonly HALF_ONE: number = 0.5;

  /**
   * Number of value: -1.
   */
  static readonly MINUS_ONE: number = -1;

  /**
   * Font weight.
   */
  static readonly FONT_WEIGHT: number = 500;

  /**
   * One hundred percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * Recent text height.
   */
  static readonly RECENT_TEXT_HEIGHT: string = '2.7%';

  /**
   * Recent text width.
   */
  static readonly RECENT_TEXT_WIDTH: string = '48.9%';

  /**
   * Delete image height.
   */
  static readonly DELETE_IMAGE_HEIGHT: string = '3.1%';

  /**
   * Delete image width.
   */
  static readonly DELETE_IMAGE_WIDTH: string = '6.7%';

  /**
   * No search image height.
   */
  static readonly NO_SEARCH_IMAGE_HEIGHT: string = '15.4%';

  /**
   * No search image width.
   */
  static readonly NO_SEARCH_IMAGE_WIDTH: string = '33.3%';

  /**
   * No search text height.
   */
  static readonly NO_SEARCH_TEXT_HEIGHT: string = '2.7%';

  /**
   * No search text width.
   */
  static readonly NO_SEARCH_TEXT_WIDTH: string = '26.7%';

  /**
   * Flew layout padding top.
   */
  static readonly FLEX_PADDING_TOP: string = '0.8%';

  /**
   * Flew layout padding bottom.
   */
  static readonly FLEX_PADDING_BOTTOM: string = '0.8%';

  /**
   * Flew layout padding left.
   */
  static readonly FLEX_PADDING_LEFT: string = '4.4%';

  /**
   * Flew layout padding right.
   */
  static readonly FLEX_PADDING_RIGHT: string = '4.4%';

  /**
   * Search input height.
   */
  static readonly SEARCH_HEIGHT: string = '5.1%';

  /**
   * Search input width.
   */
  static readonly SEARCH_WIDTH: string = '70%';

  /**
   * Text max line.
   */
  static readonly TEXT_MAX_LINE: number = 2;

  /**
   * Search placeholder.
   */
  static readonly SEARCH_PLACEHOLDER: string = '搜索...';

  /**
   * Layout weight.
   */
  static readonly LAYOUT_ClEAN_WEIGHT: number = 8;

  /**
   * Search icon.
   */
  static readonly SEARCH_ICON: string = '/resources/base/media/ic_search.png';
}